export const error = {

    INVALID_EMAIL : "INVALID_EMAIL",
    INVALID_PASSWORD : "INVALID_PASSWORD",
    INVALID_CONFIRM_PASSWORD : "INVALID_CONFIRM_PASSWORD",
    NOT_MATCHING_PASSWORDS : "NOT_MATCHING_PASSWORDS",
    
}